name: laine
favicon: null
layout_spectrum: 0.8937785876914859
typography_spectrum: 0.6012207181192935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1998972638975829
  lightness: 0.20245469082146883
  saturation: 0.3512452756986022
  rhythmicContrast: 0.07686481694690883
purpose: []
